name: lint, check format and test

on:
  push:
  workflow_dispatch:

jobs:
  lint-fmt-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Lint
        run: deno lint

      - name: Check format
        run: deno fmt --check

      - name: Run tests
        run: deno test
