name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Create a tag
        run: |
          TAG_NAME="v$(cat deno.json | jq '.version')"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"

      - name: Publish package
        run: npx jsr publish
